### ISSUE TITLE
Using prior instead of hyperprior for group level prediction in section 4.6.2

### ISSUE THREAD

**Issue by JeanLuc001** [BayesianModelingandComputationInPython/BookCode_Edition1#132]
Model `model_hierarchical_salad_sales_predictions` in listing 4.17 is

```
@tfd.JointDistributionCoroutine
def out_of_sample_prediction_model():
    model = yield root(non_centered_model)
    β = model.beta_offset * model.beta_sigma[..., None] + model.beta_mu[..., None]
    
    β_group = yield tfd.Normal(
        model.beta_mu, model.beta_sigma, name="group_beta_prediction")
    group_level_prediction = yield tfd.Normal(
        β_group * out_of_sample_customers,
        model.sigma_prior,
        name="group_level_prediction")
    for l in [2, 4]:
        yield tfd.Normal(
            tf.gather(β, l, axis=-1) * out_of_sample_customers,
            tf.gather(model.sigma, l, axis=-1),
            name=f"location_{l}_prediction")
```

In the distribution for `group_level_prediction`, `model.sigma_prior` is used for the standard deviation. However, `model.sigma_prior` is the distribution of the hyperprior, not the prior that goes into the model.

I don't understand this. Shouldn't the standard deviation in `group_level_prediction` be a half-normal distribution whose scaling parameter in turn is influenced by the hyperprior, like this (see `s = ...` as well as the line afterwards):

```
@tfd.JointDistributionCoroutine
def out_of_sample_prediction_model():
    model = yield root(non_centered_model)
    β = model.beta_offset * model.beta_sigma[..., None] + model.beta_mu[..., None]
    
    β_group = yield tfd.Normal(
        model.beta_mu, model.beta_sigma, name="group_beta_prediction")
    s = yield tfd.HalfNormal(model.sigma_prior, name="s")
    group_level_prediction = yield tfd.Normal(
        β_group * out_of_sample_customers,
        s,
        name="group_level_prediction")
    for l in [2, 4]:
        yield tfd.Normal(
            tf.gather(β, l, axis=-1) * out_of_sample_customers,
            tf.gather(model.sigma, l, axis=-1),
            name=f"location_{l}_prediction")
```

**Comment by junpenglao** [comment]
For the group level prediction, we are using hyper prior - the reason is that, hyper-prior could be considered as the average effect for each specific group/category here. So when you want group level prediction, you can use these hyper-prior directly. You could see in Code block 4.18 where we use a HalfNormal (like what you did in the code) for a new hypothetical group.

**Comment by JeanLuc001** [comment]
Thanks for the fast response.

What would you do if the hyperprior and the prior had different distributions, not both half-normal like in the book example? Or does this not matter?

**Comment by junpenglao** [comment]
It does not matter as long as you are considering the hyper parameter as the group average, and each group is a small variation on top of the group average. For example, say we are assigning a fix prior `sigma_group = yield tfd.Sample(tfd.Normal(10, .01), num_groups)`, then I usually interpreted the group average being 10, and if I want to generate sample to indicate group average effect i will just use 10 as the standard deviation. 
But there is a subtly here: what about other parameterization like 
```
sigma_group = yield tfd.Sample(tfd.HalfNormal(1), num_groups)
```
or 
```
sigma_group = yield tfd.Sample(tfd.Gamma(a, b), num_groups)
```
Here, we should be a bit more careful to instead find the expected value of the distribution `tfd.HalfNormal(1)` and `tfd.Gamma(a, b)` (`a` and `b` is hyper parameters). We didnt do that in the book because the posterior is mostly Gaussian like, but I think this is something we will add a bit more clarity in the 2nd Edition.
