### ISSUE TITLE
Manuscript Error: 

### ISSUE THREAD

**Issue by aaelony** [BayesianModelingandComputationInPython/BookCode_Edition1#154]
Manuscript code requires bambi package, please add to the environment.yml file.

# Description
bambi library mentioned on page xix, `Code 0.2` section, but not included in the `environment.yml` file so running the code on page xix yields a runtime error.

**Reference**
page xix

**Comment by aaelony** [comment]
also, although probably obvious, to make the code run `import matplotlib.pyplot as plt` should be added to `page xix` code as well.

**Comment by canyon289** [comment]
hey @aaelony the code is not meant to be runnable if copy and pasted just from the code blocks in the book itself. This is because if we included all the code needed to run every code block throughout the book most of the book would be boilerplate code!


 To run the code use the notebooks included, here for example. All these notebooks run end to end with the environment file. Let me know if this makes sense!
https://bayesiancomputationbook.com/notebooks/chp_01.html

**Comment by canyon289** [comment]
> also, `Code 1.5` on page 9 has an extra trailing parenthesis.

I took a look but couldn't find it, is it this code block?
https://bayesiancomputationbook.com/notebooks/chp_01.html
![image](https://user-images.githubusercontent.com/7213793/169091009-2942caba-a258-4562-a491-cce85d193b7a.png)

**Comment by aaelony** [comment]
I have the printed edition and am typing the code as I read.  I am finding many things that cause runtime errors (all easily fixable).  If it isn't helpful to report these issues, I can refrain but it might make the book stronger in the next edition to fix these.

@canyon289, from what you posted above, it looks like the online edition already has fixed the typo in the printed edition.

**Comment by aaelony** [comment]
Great! I'm actually a longtime R user mostly reading the book to see how these same things are done in Python. 
Thanks for the responses.
